import Head from "next/head";
import React from "react";

import Header from "../header";
import Content from "./Content";

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>Thullo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div>
        <Header />
        <main className="container mx-auto flex flex-col">
          <Content />
          <div className="m-4 h-screen rounded-xl bg-[#F8F9FD] p-5">{children}</div>
        </main>
      </div>
    </>
  );
};

export default Layout;
