import Head from "next/head";
import React from "react";

import Header from "../header";

const HeaderLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <title>Thullo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <div>
        <Header />
        {children}
      </div>
    </>
  );
};

export default HeaderLayout;
